test credential endpoint.
MatiousCorp/promptify-automation pull request #21
Opened 2024-01-26 16:57 UTC by Sadhr

2024-01-26 17:02 UTC, belyas requested changes

2024-01-26 17:02 UTC, belyas commented on packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
> +	return helper.testCredentials(user, credentials.type, credentials);
Can't we reuse `CredentialsService` instead of taking all those parts and putting them here?

2024-01-26 17:02 UTC, belyas commented on packages/cli/src/PublicApi/v1/handlers/credentials/spec/schemas/credentialTest.yml
> +          organizationId:
not all nodes will have same data object, why do we have these specific properties?

2024-01-26 17:02 UTC, belyas commented on packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
> +				}
we don't need sharing logic here, please remove it from this operation, only owners can go through.

2024-01-26 17:03 UTC, Sadhr commented on packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
> +	return helper.testCredentials(user, credentials.type, credentials);
Of course we can

2024-01-29 08:48 UTC, belyas commented on packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
> +	return helper.testCredentials(user, credentials.type, credentials);
Something like this should do it:

```ts
const { credentials } = req.body;
const credentialId = credentials.id;
const { ownsCredential } = await EECredentials.isOwned(req.user, credentialId);

return CredentialsService.test(req.user, mergedCredentials);
```

2024-01-29 12:21 UTC, belyas requested changes

2024-01-29 12:21 UTC, belyas commented on packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
> +import { type IDataObject, type INodeProperties, type INodePropertyOptions } from 'n8n-workflow';
Please revert this back, we only inject `type` inside if we have non types in the same imports

2024-01-29 14:56 UTC, belyas approved these changes

2024-01-29 14:57 UTC, merged